### ISSUE TITLE
Need work: horizontal scrolling and gaps

### ISSUE THREAD

**Issue by melissamcewen** [Bruhnk/f1-3-c2p1-colmar-academy#2]
So you don't usually want horizontal scrolling unless a site is designed for it, which is extremely rare. When you see it on a site like this it usually means something is too wide. What I do to find the culprit is use Chrome Inspector to highlight and hide different things until I find the culprit. 
![colmar_academy_padding](https://user-images.githubusercontent.com/1251094/35889572-b718a912-0b61-11e8-94b1-2b08ffae726c.jpg)

I think the header is the issue, once I removed the padding the issue went away. You can use padding on the inside elements to get them looking right, but if you use padding on the structure elements like header it can affect the entire layout of the page.

![colmar_academy](https://user-images.githubusercontent.com/1251094/35889576-c322d4f8-0b61-11e8-9bc4-dd28a0f472c8.jpg)

But then I realized #practice was causing it too, I thin the issue here is using  min-width. 
![colmar_academy_big](https://user-images.githubusercontent.com/1251094/35889586-d28ef6d8-0b61-11e8-87b0-7ca2ee82af1e.jpg)

Min-width means that that div always has to be that width which should be avoided whenever possible in responsive sites, which should adjust sizes based on screen size. Of course when I removed it, the picture is too big, but we can use responsive adjustment to fix that ratio. 
```css
.practice-main {
    width: 60%;
}

.campus-info {
    display: flex;
    flex-direction: column;
    width: 40%;
    padding: 2rem 0;

}
```

then on the img itself make it responsive with:
```css
.img-practice img {
    display: block;
    width: 100%;
}
```
